import AppKit

/// What is on the clipboard, and the two shapes the app is allowed to use it in.
///
/// This is the only place the app reads the clipboard for anything other than pasting, so the
/// limits live here rather than at the call site. One of them is not negotiable: a clipboard a
/// password manager marked concealed is never read at all. Clipboards hold passwords, keys and
/// other people's private messages — the feature is worth having only if that one never slips.
///
/// The two shapes are deliberately different. `reference` goes to the on-device model, capped,
/// and never comes back out. `appended` goes into the paste verbatim, because a stack trace or a
/// block of code that has been shortened or reworded is worse than useless — but it goes only
/// into the field the user was already about to paste into, and nowhere else.
enum ClipboardContext {
    /// Enough for an email, a stack trace or a page of notes; short enough that the model still
    /// answers inside its timeout. A copied document would blow both. This caps what the *model*
    /// is shown, never what is pasted.
    static let referenceLimit = 2000

    /// The token the on-device model is asked to leave standing where the clipboard goes.
    ///
    /// Deliberately not prose: the model has to reproduce it character for character, and anything
    /// that reads like words gets tidied into different words. Brackets and capitals are the shape
    /// a small model copies most reliably, and no dictated sentence contains them by accident.
    static let marker = "[[CLIPBOARD]]"

    /// Types that mean "this was not meant to be kept". `ConcealedType` is what 1Password and the
    /// other managers set on a copied password; the rest are the same convention for clipboard
    /// managers, and anything wearing one of them is exactly what must not end up in a prompt.
    private static let concealed: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
    ]

    static func current() -> String? {
        read(from: .general)
    }

    /// Split out from `current()` so a test can drive a private pasteboard. Nothing in the suite
    /// may touch `NSPasteboard.general` — it belongs to whoever is running the tests.
    static func read(from pasteboard: NSPasteboard) -> String? {
        let types = (pasteboard.types ?? []).map(\.rawValue)
        guard !types.contains(where: concealed.contains) else { return nil }

        guard let raw = pasteboard.string(forType: .string) else { return nil }

        let trimmed = raw.trimmingCharacters(in: .whitespacesAndNewlines)
        return trimmed.isEmpty ? nil : trimmed
    }

    /// The clipboard as the on-device model sees it: capped, because the model has a timeout.
    ///
    /// The head, not the tail: what you copied usually starts with the part you care about, and
    /// the ellipsis tells the model the text stops mid-thought rather than mid-sentence.
    static func reference(_ text: String) -> String {
        guard text.count > referenceLimit else { return text }
        return String(text.prefix(referenceLimit)) + "…"
    }

    /// The clipboard as it is pasted: after the dictated text, separated by a blank line, exactly
    /// as it was copied.
    ///
    /// Uncapped and untouched on purpose. The user copied this to paste it; a version the app
    /// trimmed to fit a model's context window would be a silently corrupted paste, and pressing
    /// ⌘V themselves would have given them the whole thing.
    static func appended(_ clipboard: String?, to text: String) -> String {
        guard let clipboard, !clipboard.isEmpty else { return text }
        guard !text.isEmpty else { return clipboard }
        return text + "\n\n" + clipboard
    }

    /// The clipboard put where the user said it goes.
    ///
    /// Saying the placeholder — "clipboard content" unless the mode says otherwise — is how you
    /// wrap what you copied in a sentence instead of leaving it dangling at the end: *"here is the
    /// error I keep getting, clipboard content, what does it mean?"*. Every occurrence is
    /// replaced, because saying it twice means twice.
    ///
    /// Two ways of finding the spot, in order. The model is asked to leave `marker` where the user
    /// asked for the clipboard, so when the marker is there the position is exact and there is
    /// nothing to match — the model did the judging, which is the part it is good at, and handed
    /// back a literal, which is the part a rule is good at. That covers the case a rule cannot:
    /// the placeholder reworded, reordered or absorbed into the sentence around it.
    ///
    /// Without the marker — the model is off, the mode has no instructions, or it ignored the
    /// request — the spoken phrase is matched directly, loosely enough to survive the ending it
    /// picked up on the way through the speech recogniser. Failing that the clipboard goes to the
    /// end, which is where it would have gone with no placeholder at all.
    ///
    /// What does *not* change is the ordering: this runs after the whole refinement pipeline, so
    /// the model is never shown the text it is about to reproduce. Showing it gets a stack trace
    /// reworded, and the length check in `OnDeviceRefiner` would then throw the answer away for
    /// growing.
    static func substituted(_ clipboard: String?, into text: String, placeholder: String) -> String {
        // No clipboard, so a marker has nothing to stand for and must not reach the document.
        guard let clipboard, !clipboard.isEmpty else { return removingMarker(from: text) }

        if text.range(of: marker, options: .caseInsensitive) != nil {
            // A plain string replacement, so nothing in the clipboard is read as regex syntax.
            return text.replacingOccurrences(of: marker, with: clipboard, options: .caseInsensitive)
        }

        let phrase = placeholder.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !phrase.isEmpty, let regex = RuleRefiner.cachedInflectedRegex(for: phrase) else {
            return appended(clipboard, to: text)
        }

        let range = NSRange(text.startIndex..., in: text)
        guard regex.firstMatch(in: text, range: range) != nil else {
            return appended(clipboard, to: text)
        }

        // Escaped: a clipboard holding "$1" or "\\" is text, not a substitution template.
        return regex.stringByReplacingMatches(
            in: text,
            range: range,
            withTemplate: NSRegularExpression.escapedTemplate(for: clipboard)
        )
    }

    /// True when what the user said plausibly names the clipboard at all.
    ///
    /// This is what decides whether the model is asked for the marker in the first place. The
    /// model gets to say *where* the clipboard goes, never *whether* it was asked for: a marker
    /// invented over a sentence that never mentioned the clipboard would drop it mid-thought,
    /// which is worse than the end.
    ///
    /// Only the first word, and matched as a substring rather than a whole word, because a loose
    /// net is exactly what is wanted here — "буфера" and "clipboard's" both have to count. The
    /// precise judgement is the model's job; this only rules out the sentences where there is
    /// nothing to judge.
    static func mentioned(_ placeholder: String, in text: String) -> Bool {
        guard let head = placeholder.split(whereSeparator: \.isWhitespace).first else { return false }
        return text.range(of: String(head), options: [.caseInsensitive, .diacriticInsensitive]) != nil
    }

    /// Takes out a marker that has nothing to stand for, and closes the gap it leaves.
    ///
    /// Reached when the clipboard turned out to be empty or concealed after the model had already
    /// been asked to place it. The three passes are the punctuation the marker was sitting
    /// between: "the error, [[CLIPBOARD]], what?" has to come back as "the error, what?" rather
    /// than "the error, , what?".
    static func removingMarker(from text: String) -> String {
        guard text.range(of: marker, options: .caseInsensitive) != nil else { return text }

        var result = text.replacingOccurrences(of: marker, with: "", options: .caseInsensitive)
        result = replacing(#"([,;:])[ \t]*([,.!?;:])"#, in: result, with: "$2")
        result = replacing(#"[ \t]{2,}"#, in: result, with: " ")
        result = replacing(#"[ \t]+([,.!?;:])"#, in: result, with: "$1")
        return result.trimmingCharacters(in: .whitespacesAndNewlines)
    }

    private static func replacing(_ pattern: String, in text: String, with template: String) -> String {
        guard let regex = RuleRefiner.cachedRegex(pattern) else { return text }
        return regex.stringByReplacingMatches(
            in: text,
            range: NSRange(text.startIndex..., in: text),
            withTemplate: template
        )
    }
}
