import AppKit

/// What is on the clipboard, prepared for the on-device model to read as reference.
///
/// This is the only place the app reads the clipboard for anything other than pasting, so the
/// limits live here rather than at the call site. Two of them are not negotiable: a clipboard a
/// password manager marked concealed is never read at all, and what is read only ever reaches the
/// on-device model. Clipboards hold passwords, keys and other people's private messages — the
/// feature is worth having only if none of that can leave the Mac.
enum ClipboardContext {
    /// Enough for an email, a stack trace or a page of notes; short enough that the model still
    /// answers inside its timeout. A copied document would blow both.
    static let characterLimit = 2000

    /// Types that mean "this was not meant to be kept". `ConcealedType` is what 1Password and the
    /// other managers set on a copied password; the rest are the same convention for clipboard
    /// managers, and anything wearing one of them is exactly what must not end up in a prompt.
    private static let concealed: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
    ]

    static func current() -> String? {
        read(from: .general)
    }

    /// Split out from `current()` so a test can drive a private pasteboard. Nothing in the suite
    /// may touch `NSPasteboard.general` — it belongs to whoever is running the tests.
    static func read(from pasteboard: NSPasteboard) -> String? {
        let types = (pasteboard.types ?? []).map(\.rawValue)
        guard !types.contains(where: concealed.contains) else { return nil }

        guard let raw = pasteboard.string(forType: .string) else { return nil }

        let trimmed = raw.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else { return nil }

        // The head, not the tail: what you copied usually starts with the part you care about,
        // and the ellipsis tells the model the text stops mid-thought rather than mid-sentence.
        guard trimmed.count > characterLimit else { return trimmed }
        return String(trimmed.prefix(characterLimit)) + "…"
    }
}
